const INVENTORY_MOVEMENT_TYPE = Object.freeze({
  PURCHASE: 'PURCHASE',
  RESTOCK: 'RESTOCK',
  ORDER_RESERVED: 'ORDER_RESERVED',
  ORDER_COMMITTED: 'ORDER_COMMITTED',
  ORDER_CANCELLED: 'ORDER_CANCELLED',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  RETURN_APPROVED: 'RETURN_APPROVED',
  REFUND_APPROVED: 'REFUND_APPROVED',
  MANUAL_ADJUSTMENT: 'MANUAL_ADJUSTMENT',
  DAMAGED: 'DAMAGED',
  STOCK_CORRECTION: 'STOCK_CORRECTION',
  TRANSFER: 'TRANSFER',
});

const INVENTORY_MOVEMENT_TYPE_LIST = Object.freeze(Object.values(INVENTORY_MOVEMENT_TYPE));

const INVENTORY_RESERVATION_STATUS = Object.freeze({
  ACTIVE: 'ACTIVE',
  COMMITTED: 'COMMITTED',
  RELEASED: 'RELEASED',
  EXPIRED: 'EXPIRED',
});

const INVENTORY_RESERVATION_STATUS_LIST = Object.freeze(Object.values(INVENTORY_RESERVATION_STATUS));

const INVENTORY_REFERENCE_TYPES = Object.freeze({
  ORDER: 'ORDER',
  PAYMENT: 'PAYMENT',
  ADMIN: 'ADMIN',
  SYSTEM: 'SYSTEM',
});

module.exports = {
  INVENTORY_MOVEMENT_TYPE,
  INVENTORY_MOVEMENT_TYPE_LIST,
  INVENTORY_RESERVATION_STATUS,
  INVENTORY_RESERVATION_STATUS_LIST,
  INVENTORY_REFERENCE_TYPES,
};
