const { ROLES } = require('./roles');

const PERMISSIONS = Object.freeze({
  ADMIN_MANAGE: 'admin.manage',
  PRODUCT_CREATE: 'product.create',
  PRODUCT_UPDATE: 'product.update',
  PRODUCT_DELETE: 'product.delete',
  PRODUCT_READ: 'product.read',
  ORDER_READ: 'order.read',
  ORDER_UPDATE: 'order.update',
});

const ALL_PERMISSIONS = Object.freeze(Object.values(PERMISSIONS));

const ROLE_PERMISSION_MATRIX = Object.freeze({
  [ROLES.DEVELOPER]: ['*'],
  [ROLES.SUPER_ADMIN]: [
    PERMISSIONS.ADMIN_MANAGE,
    PERMISSIONS.PRODUCT_CREATE,
    PERMISSIONS.PRODUCT_UPDATE,
    PERMISSIONS.PRODUCT_DELETE,
    PERMISSIONS.PRODUCT_READ,
    PERMISSIONS.ORDER_READ,
    PERMISSIONS.ORDER_UPDATE,
  ],
  [ROLES.ADMIN]: [
    PERMISSIONS.PRODUCT_CREATE,
    PERMISSIONS.PRODUCT_UPDATE,
    PERMISSIONS.PRODUCT_DELETE,
    PERMISSIONS.PRODUCT_READ,
    PERMISSIONS.ORDER_READ,
    PERMISSIONS.ORDER_UPDATE,
  ],
  [ROLES.CUSTOMER]: [PERMISSIONS.PRODUCT_READ],
});

module.exports = {
  PERMISSIONS,
  ALL_PERMISSIONS,
  ROLE_PERMISSION_MATRIX,
};
