const { ROLES } = require('./roles');
const { REVIEW_FEATURE_KEYS } = require('./review');

const PERMISSIONS = Object.freeze({
  ADMIN_MANAGE: 'admin.manage',
  PRODUCT_CREATE: 'product.create',
  PRODUCT_UPDATE: 'product.update',
  PRODUCT_DELETE: 'product.delete',
  PRODUCT_READ: 'product.read',
  ORDER_READ: 'order.read',
  ORDER_UPDATE: 'order.update',
  COUPON_CREATE: 'coupon.create',
  COUPON_UPDATE: 'coupon.update',
  COUPON_READ: 'coupon.read',
  COUPON_DELETE: 'coupon.delete',
  INVENTORY_READ: 'inventory.read',
  INVENTORY_ADJUST: 'inventory.adjust',
  INVENTORY_MANAGE: 'inventory.manage',
  REVIEW_CREATE: 'review.create',
  REVIEW_UPDATE: 'review.update',
  REVIEW_DELETE: 'review.delete',
  REVIEW_READ: 'review.read',
  REVIEW_MODERATE: 'review.moderate',
  REVIEW_REPLY: 'review.reply',
});

const ALL_PERMISSIONS = Object.freeze([
  ...Object.values(PERMISSIONS),
  ...Object.values(REVIEW_FEATURE_KEYS),
]);

const ROLE_PERMISSION_MATRIX = Object.freeze({
  [ROLES.DEVELOPER]: ['*'],
  [ROLES.SUPER_ADMIN]: [
    PERMISSIONS.ADMIN_MANAGE,
    PERMISSIONS.PRODUCT_CREATE,
    PERMISSIONS.PRODUCT_UPDATE,
    PERMISSIONS.PRODUCT_DELETE,
    PERMISSIONS.PRODUCT_READ,
    PERMISSIONS.ORDER_READ,
    PERMISSIONS.ORDER_UPDATE,
    PERMISSIONS.COUPON_CREATE,
    PERMISSIONS.COUPON_UPDATE,
    PERMISSIONS.COUPON_READ,
    PERMISSIONS.COUPON_DELETE,
    PERMISSIONS.INVENTORY_READ,
    PERMISSIONS.INVENTORY_ADJUST,
    PERMISSIONS.INVENTORY_MANAGE,
    PERMISSIONS.REVIEW_CREATE,
    PERMISSIONS.REVIEW_UPDATE,
    PERMISSIONS.REVIEW_DELETE,
    PERMISSIONS.REVIEW_READ,
    PERMISSIONS.REVIEW_MODERATE,
    PERMISSIONS.REVIEW_REPLY,
  ],
  [ROLES.ADMIN]: [
    PERMISSIONS.PRODUCT_CREATE,
    PERMISSIONS.PRODUCT_UPDATE,
    PERMISSIONS.PRODUCT_DELETE,
    PERMISSIONS.PRODUCT_READ,
    PERMISSIONS.ORDER_READ,
    PERMISSIONS.ORDER_UPDATE,
    PERMISSIONS.COUPON_CREATE,
    PERMISSIONS.COUPON_UPDATE,
    PERMISSIONS.COUPON_READ,
    PERMISSIONS.COUPON_DELETE,
    PERMISSIONS.INVENTORY_READ,
    PERMISSIONS.INVENTORY_ADJUST,
    PERMISSIONS.INVENTORY_MANAGE,
    PERMISSIONS.REVIEW_READ,
    PERMISSIONS.REVIEW_MODERATE,
    PERMISSIONS.REVIEW_REPLY,
  ],
  [ROLES.CUSTOMER]: [
    PERMISSIONS.PRODUCT_READ,
    PERMISSIONS.REVIEW_CREATE,
    PERMISSIONS.REVIEW_UPDATE,
    PERMISSIONS.REVIEW_DELETE,
    PERMISSIONS.REVIEW_READ,
  ],
});

module.exports = {
  PERMISSIONS,
  ALL_PERMISSIONS,
  ROLE_PERMISSION_MATRIX,
};
